version: '3.10'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn hulisite.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgrest/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - '1337:80'
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:

